<?php declare( strict_types=1 );

namespace FernleafSystems\ApiWrappers\Calendly\Endpoint\EventTypes;

use FernleafSystems\ApiWrappers\Calendly\Endpoint\Common;

class Retrieve extends Base {

	use Common\SingleResourceRetrieve;

	public function retrieve() :EventTypeVO {
		return $this->sendRequestWithVoResponse();
	}

	protected function getVO() {
		return new EventTypeVO(); // TODO: Change the autogenerated stub
	}

	protected function getUrlEndpoint() :string {
		return sprintf( '/event_types/%s', $this->getUUID() );
	}
}